
/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        gray1: "var(--gray-1)",
        gray2: "var(--gray-2)",
        gray3: "var(--gray-3)",
        gray4: "var(--gray-4)",
        gray5: "var(--gray-5)",
        gray6: "var(--gray-6)",
        gray7: "var(--gray-7)",
        gray8: "var(--gray-8)",
        gray9: "var(--gray-9)",
        gray10: "var(--gray-10)",
        gray11: "var(--gray-11)",
        gray12: "var(--gray-12)",

        mauve1: "var(--mauve-1)",
        mauve2: "var(--mauve-2)",
        mauve3: "var(--mauve-3)",
        mauve4: "var(--mauve-4)",
        mauve5: "var(--mauve-5)",
        mauve6: "var(--mauve-6)",
        mauve7: "var(--mauve-7)",
        mauve8: "var(--mauve-8)",
        mauve9: "var(--mauve-9)",
        mauve10: "var(--mauve-10)",
        mauve11: "var(--mauve-11)",
        mauve12: "var(--mauve-12)",

        slate1: "var(--slate-1)",
        slate2: "var(--slate-2)",
        slate3: "var(--slate-3)",
        slate4: "var(--slate-4)",
        slate5: "var(--slate-5)",
        slate6: "var(--slate-6)",
        slate7: "var(--slate-7)",
        slate8: "var(--slate-8)",
        slate9: "var(--slate-9)",
        slate10: "var(--slate-10)",
        slate11: "var(--slate-11)",
        slate12: "var(--slate-12)",

        sage1: "var(--sage-1)",
        sage2: "var(--sage-2)",
        sage3: "var(--sage-3)",
        sage4: "var(--sage-4)",
        sage5: "var(--sage-5)",
        sage6: "var(--sage-6)",
        sage7: "var(--sage-7)",
        sage8: "var(--sage-8)",
        sage9: "var(--sage-9)",
        sage10: "var(--sage-10)",
        sage11: "var(--sage-11)",
        sage12: "var(--sage-12)",

        olive1: "var(--olive-1)",
        olive2: "var(--olive-2)",
        olive3: "var(--olive-3)",
        olive4: "var(--olive-4)",
        olive5: "var(--olive-5)",
        olive6: "var(--olive-6)",
        olive7: "var(--olive-7)",
        olive8: "var(--olive-8)",
        olive9: "var(--olive-9)",
        olive10: "var(--olive-10)",
        olive11: "var(--olive-11)",
        olive12: "var(--olive-12)",

        sand1: "var(--sand-1)",
        sand2: "var(--sand-2)",
        sand3: "var(--sand-3)",
        sand4: "var(--sand-4)",
        sand5: "var(--sand-5)",
        sand6: "var(--sand-6)",
        sand7: "var(--sand-7)",
        sand8: "var(--sand-8)",
        sand9: "var(--sand-9)",
        sand10: "var(--sand-10)",
        sand11: "var(--sand-11)",
        sand12: "var(--sand-12)",

        gold1: "var(--gold-1)",
        gold2: "var(--gold-2)",
        gold3: "var(--gold-3)",
        gold4: "var(--gold-4)",
        gold5: "var(--gold-5)",
        gold6: "var(--gold-6)",
        gold7: "var(--gold-7)",
        gold8: "var(--gold-8)",
        gold9: "var(--gold-9)",
        gold10: "var(--gold-10)",
        gold11: "var(--gold-11)",
        gold12: "var(--gold-12)",

        bronze1: "var(--bronze-1)",
        bronze2: "var(--bronze-2)",
        bronze3: "var(--bronze-3)",
        bronze4: "var(--bronze-4)",
        bronze5: "var(--bronze-5)",
        bronze6: "var(--bronze-6)",
        bronze7: "var(--bronze-7)",
        bronze8: "var(--bronze-8)",
        bronze9: "var(--bronze-9)",
        bronze10: "var(--bronze-10)",
        bronze11: "var(--bronze-11)",
        bronze12: "var(--bronze-12)",

        brown1: "var(--brown-1)",
        brown2: "var(--brown-2)",
        brown3: "var(--brown-3)",
        brown4: "var(--brown-4)",
        brown5: "var(--brown-5)",
        brown6: "var(--brown-6)",
        brown7: "var(--brown-7)",
        brown8: "var(--brown-8)",
        brown9: "var(--brown-9)",
        brown10: "var(--brown-10)",
        brown11: "var(--brown-11)",
        brown12: "var(--brown-12)",

        yellow1: "var(--yellow-1)",
        yellow2: "var(--yellow-2)",
        yellow3: "var(--yellow-3)",
        yellow4: "var(--yellow-4)",
        yellow5: "var(--yellow-5)",
        yellow6: "var(--yellow-6)",
        yellow7: "var(--yellow-7)",
        yellow8: "var(--yellow-8)",
        yellow9: "var(--yellow-9)",
        yellow10: "var(--yellow-10)",
        yellow11: "var(--yellow-11)",
        yellow12: "var(--yellow-12)",

        amber1: "var(--amber-1)",
        amber2: "var(--amber-2)",
        amber3: "var(--amber-3)",
        amber4: "var(--amber-4)",
        amber5: "var(--amber-5)",
        amber6: "var(--amber-6)",
        amber7: "var(--amber-7)",
        amber8: "var(--amber-8)",
        amber9: "var(--amber-9)",
        amber10: "var(--amber-10)",
        amber11: "var(--amber-11)",
        amber12: "var(--amber-12)",

        orange1: "var(--orange-1)",
        orange2: "var(--orange-2)",
        orange3: "var(--orange-3)",
        orange4: "var(--orange-4)",
        orange5: "var(--orange-5)",
        orange6: "var(--orange-6)",
        orange7: "var(--orange-7)",
        orange8: "var(--orange-8)",
        orange9: "var(--orange-9)",
        orange10: "var(--orange-10)",
        orange11: "var(--orange-11)",
        orange12: "var(--orange-12)",

        tomato1: "var(--tomato-1)",
        tomato2: "var(--tomato-2)",
        tomato3: "var(--tomato-3)",
        tomato4: "var(--tomato-4)",
        tomato5: "var(--tomato-5)",
        tomato6: "var(--tomato-6)",
        tomato7: "var(--tomato-7)",
        tomato8: "var(--tomato-8)",
        tomato9: "var(--tomato-9)",
        tomato10: "var(--tomato-10)",
        tomato11: "var(--tomato-11)",
        tomato12: "var(--tomato-12)",

        red1: "var(--red-1)",
        red2: "var(--red-2)",
        red3: "var(--red-3)",
        red4: "var(--red-4)",
        red5: "var(--red-5)",
        red6: "var(--red-6)",
        red7: "var(--red-7)",
        red8: "var(--red-8)",
        red9: "var(--red-9)",
        red10: "var(--red-10)",
        red11: "var(--red-11)",
        red12: "var(--red-12)",

        ruby1: "var(--ruby-1)",
        ruby2: "var(--ruby-2)",
        ruby3: "var(--ruby-3)",
        ruby4: "var(--ruby-4)",
        ruby5: "var(--ruby-5)",
        ruby6: "var(--ruby-6)",
        ruby7: "var(--ruby-7)",
        ruby8: "var(--ruby-8)",
        ruby9: "var(--ruby-9)",
        ruby10: "var(--ruby-10)",
        ruby11: "var(--ruby-11)",
        ruby12: "var(--ruby-12)",

        crimson1: "var(--crimson-1)",
        crimson2: "var(--crimson-2)",
        crimson3: "var(--crimson-3)",
        crimson4: "var(--crimson-4)",
        crimson5: "var(--crimson-5)",
        crimson6: "var(--crimson-6)",
        crimson7: "var(--crimson-7)",
        crimson8: "var(--crimson-8)",
        crimson9: "var(--crimson-9)",
        crimson10: "var(--crimson-10)",
        crimson11: "var(--crimson-11)",
        crimson12: "var(--crimson-12)",

        pink1: "var(--pink-1)",
        pink2: "var(--pink-2)",
        pink3: "var(--pink-3)",
        pink4: "var(--pink-4)",
        pink5: "var(--pink-5)",
        pink6: "var(--pink-6)",
        pink7: "var(--pink-7)",
        pink8: "var(--pink-8)",
        pink9: "var(--pink-9)",
        pink10: "var(--pink-10)",
        pink11: "var(--pink-11)",
        pink12: "var(--pink-12)",

        plum1: "var(--plum-1)",
        plum2: "var(--plum-2)",
        plum3: "var(--plum-3)",
        plum4: "var(--plum-4)",
        plum5: "var(--plum-5)",
        plum6: "var(--plum-6)",
        plum7: "var(--plum-7)",
        plum8: "var(--plum-8)",
        plum9: "var(--plum-9)",
        plum10: "var(--plum-10)",
        plum11: "var(--plum-11)",
        plum12: "var(--plum-12)",

        purple1: "var(--purple-1)",
        purple2: "var(--purple-2)",
        purple3: "var(--purple-3)",
        purple4: "var(--purple-4)",
        purple5: "var(--purple-5)",
        purple6: "var(--purple-6)",
        purple7: "var(--purple-7)",
        purple8: "var(--purple-8)",
        purple9: "var(--purple-9)",
        purple10: "var(--purple-10)",
        purple11: "var(--purple-11)",
        purple12: "var(--purple-12)",
        
        violet1: "var(--violet-1)",
        violet2: "var(--violet-2)",
        violet3: "var(--violet-3)",
        violet4: "var(--violet-4)",
        violet5: "var(--violet-5)",
        violet6: "var(--violet-6)",
        violet7: "var(--violet-7)",
        violet8: "var(--violet-8)",
        violet9: "var(--violet-9)",
        violet10: "var(--violet-10)",
        violet11: "var(--violet-11)",
        violet12: "var(--violet-12)",

        iris1: "var(--iris-1)",
        iris2: "var(--iris-2)",
        iris3: "var(--iris-3)",
        iris4: "var(--iris-4)",
        iris5: "var(--iris-5)",
        iris6: "var(--iris-6)",
        iris7: "var(--iris-7)",
        iris8: "var(--iris-8)",
        iris9: "var(--iris-9)",
        iris10: "var(--iris-10)",
        iris11: "var(--iris-11)",
        iris12: "var(--iris-12)",

        indigo1: "var(--indigo-1)",
        indigo2: "var(--indigo-2)",
        indigo3: "var(--indigo-3)",
        indigo4: "var(--indigo-4)",
        indigo5: "var(--indigo-5)",
        indigo6: "var(--indigo-6)",
        indigo7: "var(--indigo-7)",
        indigo8: "var(--indigo-8)",
        indigo9: "var(--indigo-9)",
        indigo10: "var(--indigo-10)",
        indigo11: "var(--indigo-11)",
        indigo12: "var(--indigo-12)",

        blue1: "var(--blue-1)",
        blue2: "var(--blue-2)",
        blue3: "var(--blue-3)",
        blue4: "var(--blue-4)",
        blue5: "var(--blue-5)",
        blue6: "var(--blue-6)",
        blue7: "var(--blue-7)",
        blue8: "var(--blue-8)",
        blue9: "var(--blue-9)",
        blue10: "var(--blue-10)",
        blue11: "var(--blue-11)",
        blue12: "var(--blue-12)",

        cyan1: "var(--cyan-1)",
        cyan2: "var(--cyan-2)",
        cyan3: "var(--cyan-3)",
        cyan4: "var(--cyan-4)",
        cyan5: "var(--cyan-5)",
        cyan6: "var(--cyan-6)",
        cyan7: "var(--cyan-7)",
        cyan8: "var(--cyan-8)",
        cyan9: "var(--cyan-9)",
        cyan10: "var(--cyan-10)",
        cyan11: "var(--cyan-11)",
        cyan12: "var(--cyan-12)",

        teal1: "var(--teal-1)",
        teal2: "var(--teal-2)",
        teal3: "var(--teal-3)",
        teal4: "var(--teal-4)",
        teal5: "var(--teal-5)",
        teal6: "var(--teal-6)",
        teal7: "var(--teal-7)",
        teal8: "var(--teal-8)",
        teal9: "var(--teal-9)",
        teal10: "var(--teal-10)",
        teal11: "var(--teal-11)",
        teal12: "var(--teal-12)",

        jade1: "var(--jade-1)",
        jade2: "var(--jade-2)",
        jade3: "var(--jade-3)",
        jade4: "var(--jade-4)",
        jade5: "var(--jade-5)",
        jade6: "var(--jade-6)",
        jade7: "var(--jade-7)",
        jade8: "var(--jade-8)",
        jade9: "var(--jade-9)",
        jade10: "var(--jade-10)",
        jade11: "var(--jade-11)",
        jade12: "var(--jade-12)",

        green1: "var(--green-1)",
        green2: "var(--green-2)",
        green3: "var(--green-3)",
        green4: "var(--green-4)",
        green5: "var(--green-5)",
        green6: "var(--green-6)",
        green7: "var(--green-7)",
        green8: "var(--green-8)",
        green9: "var(--green-9)",
        green10: "var(--green-10)",
        green11: "var(--green-11)",
        green12: "var(--green-12)",

        grass1: "var(--grass-1)",
        grass2: "var(--grass-2)",
        grass3: "var(--grass-3)",
        grass4: "var(--grass-4)",
        grass5: "var(--grass-5)",
        grass6: "var(--grass-6)",
        grass7: "var(--grass-7)", 
        grass8: "var(--grass-8)",
        grass9: "var(--grass-9)",
        grass10: "var(--grass-10)",
        grass11: "var(--grass-11)",
        grass12: "var(--grass-12)",

        lime1: "var(--lime-1)",
        lime2: "var(--lime-2)",
        lime3: "var(--lime-3)",
        lime4: "var(--lime-4)",
        lime5: "var(--lime-5)",
        lime6: "var(--lime-6)",
        lime7: "var(--lime-7)",
        lime8: "var(--lime-8)",
        lime9: "var(--lime-9)",
        lime10: "var(--lime-10)",
        lime11: "var(--lime-11)",
        lime12: "var(--lime-12)",

        mint1: "var(--mint-1)",
        mint2: "var(--mint-2)",
        mint3: "var(--mint-3)",
        mint4: "var(--mint-4)",
        mint5: "var(--mint-5)",
        mint6: "var(--mint-6)",
        mint7: "var(--mint-7)",
        mint8: "var(--mint-8)",
        mint9: "var(--mint-9)",
        mint10: "var(--mint-10)",
        mint11: "var(--mint-11)",
        mint12: "var(--mint-12)",

        sky1: "var(--sky-1)",
        sky2: "var(--sky-2)",
        sky3: "var(--sky-3)",
        sky4: "var(--sky-4)",
        sky5: "var(--sky-5)",
        sky6: "var(--sky-6)",
        sky7: "var(--sky-7)",
        sky8: "var(--sky-8)",
        sky9: "var(--sky-9)",
        sky10: "var(--sky-10)",
        sky11: "var(--sky-11)",
        sky12: "var(--sky-12)",
        




      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },

}